---
server:
  port: 8080
  contextPath: /AsignmentFresher12_R1

spring:
  profiles: prod
datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/TrafficTickets
    username: root
    password: 
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
      

