/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.46
 * Generated at: 2017-09-25 04:47:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\n");
      out.write("<body>\n");
      out.write("\t<div id=\"main\">\n");
      out.write("\t\t<div id=\"head\">\n");
      out.write("\t\t <img src=\"http://webcoban.vn/public/home/img_demo/h1.jpg\" width=\"2000px\" height=\"100px\">\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div id=\"head-link\">\n");
      out.write("\t\t\t<div id=\"menu\">\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Home</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Student</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">News</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Help</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Support</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div id=\"left\"></div>\n");
      out.write("\t\t<div id=\"content\">\n");
      out.write("\t\t\n");
      out.write("\t\t <img src=\"image/download.jpg\" width=\"50px\" height=\"50px\">\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div id=\"right\"></div>\n");
      out.write("\t\t<div id=\"footer\"></div>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("body {\n");
      out.write("\tfont-family: Arial, Tahoma;\n");
      out.write("\tfont-size: 12px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#main {\n");
      out.write("\twidth: auto;\n");
      out.write("\tpadding: 0;\n");
      out.write("\tmargin-left: auto;\n");
      out.write("\tmargin-right: auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#head {\n");
      out.write("\theight: 100px;\n");
      out.write("\tbackground-color: #F5F5F5;\n");
      out.write("\tborder: 1px solid #CDCDCD;\n");
      out.write("\tmargin-bottom: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#head-link {\n");
      out.write("\theight: 30px;\n");
      out.write("\tline-height: 30px;\n");
      out.write("\tpadding-left: 10px;\n");
      out.write("\tpadding-right: 10px;\n");
      out.write("\tborder: 1px solid #CDCDCD;\n");
      out.write("\tbackground-color: #F5F5F5;\n");
      out.write("\tmargin-bottom: 5px;\n");
      out.write("\tclear: both;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#left {\n");
      out.write("\twidth: 150px;\n");
      out.write("\tmin-height: 600px;\n");
      out.write("\tborder: 1px solid #CDCDCD;\n");
      out.write("\tfloat: left;\n");
      out.write("\tbackground-color: #004C00;\n");
      out.write("\tmargin-bottom: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#content {\n");
      out.write("\twidth: 600px;\n");
      out.write("\tmin-height: 600px;\n");
      out.write("\tborder: 1px solid #CDCDCD;\n");
      out.write("\tfloat: left;\n");
      out.write("\tmargin-left: 5px;\n");
      out.write("\tmargin-right: 5px;\n");
      out.write("\tmargin-bottom: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#right {\n");
      out.write("\twidth: 234px;\n");
      out.write("\tmin-height: 600px;\n");
      out.write("\tborder: 1px solid #CDCDCD;\n");
      out.write("\tfloat: right;\n");
      out.write("\tmargin-bottom: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#footer {\n");
      out.write("\theight: 200px;\n");
      out.write("\tclear: both;\n");
      out.write("\tborder: 1px solid #CDCDCD;\n");
      out.write("\tbackground-color: #F8F8FF;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#menu {\n");
      out.write("\tfont-family: sans-serif;\n");
      out.write("\tcolor: #333;\n");
      out.write("}\n");
      out.write("/*==Reset CSS==*/\n");
      out.write("* {\n");
      out.write("  margin: 0;\n");
      out.write("  padding: 0;\n");
      out.write("}\n");
      out.write("#menu ul {\n");
      out.write("  background: #1F568B;\n");
      out.write("  list-style-type: none;\n");
      out.write("  text-align: center;\n");
      out.write("}\n");
      out.write("#menu ul {\n");
      out.write("  background: #1F568B;\n");
      out.write("  list-style-type: none;\n");
      out.write("  overflow: hidden;\n");
      out.write("  width: 100%;\n");
      out.write("}\n");
      out.write("#menu a {\n");
      out.write(" font-size:15px;\n");
      out.write("  text-decoration: none;\n");
      out.write("  color: #fff;\n");
      out.write("  display: block;\n");
      out.write("}\n");
      out.write("#menu a:hover {\n");
      out.write("  background: #F1F1F1;\n");
      out.write("  color: #333;\n");
      out.write("}\n");
      out.write("#menu li {\n");
      out.write("  color: #f1f1f1;\n");
      out.write("  display: inline-block;\n");
      out.write("  width: 120px;\n");
      out.write("  height: 40px;\n");
      out.write("  line-height: 40px;\n");
      out.write("  margin-left: -5px;\n");
      out.write("}\n");
      out.write("#menu ul {\n");
      out.write("  background: #1F568B;\n");
      out.write("  list-style-type: none;\n");
      out.write("  overflow: hidden;\n");
      out.write("  width: 100%;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
