package vn.ifisolution.fresher12.entity;
// Generated Sep 27, 2017 3:33:14 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Addresses generated by hbm2java
 */
@Entity
@Table(name = "addresses", catalog = "ThienAn")
public class Addresses implements java.io.Serializable {

	private Integer addressId;
	private String line1NumberBuilding;
	private String line2NumberStreet;
	private String line3AreaLocalytiSuburb;
	private String line4Other;
	private String townCity;
	private String zipPostcode;
	private String stateProvinceCounty;
	private String country;
	private String otherAddressDetails;
	private Set<Offcers> offcerses = new HashSet<Offcers>(0);
	private Set<Violaters> violaterses = new HashSet<Violaters>(0);

	public Addresses() {
	}
	
	

	public Addresses(Integer addressId) {
		super();
		this.addressId = addressId;
	}



	public Addresses(String line1NumberBuilding, String line2NumberStreet, String line3AreaLocalytiSuburb,
			String line4Other, String townCity, String zipPostcode, String stateProvinceCounty, String country,
			String otherAddressDetails) {
		this.line1NumberBuilding = line1NumberBuilding;
		this.line2NumberStreet = line2NumberStreet;
		this.line3AreaLocalytiSuburb = line3AreaLocalytiSuburb;
		this.line4Other = line4Other;
		this.townCity = townCity;
		this.zipPostcode = zipPostcode;
		this.stateProvinceCounty = stateProvinceCounty;
		this.country = country;
		this.otherAddressDetails = otherAddressDetails;
	}

	public Addresses(String line1NumberBuilding, String line2NumberStreet, String line3AreaLocalytiSuburb,
			String line4Other, String townCity, String zipPostcode, String stateProvinceCounty, String country,
			String otherAddressDetails, Set<Offcers> offcerses, Set<Violaters> violaterses) {
		this.line1NumberBuilding = line1NumberBuilding;
		this.line2NumberStreet = line2NumberStreet;
		this.line3AreaLocalytiSuburb = line3AreaLocalytiSuburb;
		this.line4Other = line4Other;
		this.townCity = townCity;
		this.zipPostcode = zipPostcode;
		this.stateProvinceCounty = stateProvinceCounty;
		this.country = country;
		this.otherAddressDetails = otherAddressDetails;
		this.offcerses = offcerses;
		this.violaterses = violaterses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "address_id", unique = true, nullable = false)
	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

	@Column(name = "line_1_number_building", nullable = false, length = 50)
	public String getLine1NumberBuilding() {
		return this.line1NumberBuilding;
	}

	public void setLine1NumberBuilding(String line1NumberBuilding) {
		this.line1NumberBuilding = line1NumberBuilding;
	}

	@Column(name = "line_2_number_street", nullable = false, length = 50)
	public String getLine2NumberStreet() {
		return this.line2NumberStreet;
	}

	public void setLine2NumberStreet(String line2NumberStreet) {
		this.line2NumberStreet = line2NumberStreet;
	}

	@Column(name = "line_3_area_localyti_suburb", nullable = false, length = 50)
	public String getLine3AreaLocalytiSuburb() {
		return this.line3AreaLocalytiSuburb;
	}

	public void setLine3AreaLocalytiSuburb(String line3AreaLocalytiSuburb) {
		this.line3AreaLocalytiSuburb = line3AreaLocalytiSuburb;
	}

	@Column(name = "line_4_other", nullable = false, length = 50)
	public String getLine4Other() {
		return this.line4Other;
	}

	public void setLine4Other(String line4Other) {
		this.line4Other = line4Other;
	}

	@Column(name = "town_city", nullable = false, length = 50)
	public String getTownCity() {
		return this.townCity;
	}

	public void setTownCity(String townCity) {
		this.townCity = townCity;
	}

	@Column(name = "zip_postcode", nullable = false, length = 50)
	public String getZipPostcode() {
		return this.zipPostcode;
	}

	public void setZipPostcode(String zipPostcode) {
		this.zipPostcode = zipPostcode;
	}

	@Column(name = "state_province_county", nullable = false, length = 100)
	public String getStateProvinceCounty() {
		return this.stateProvinceCounty;
	}

	public void setStateProvinceCounty(String stateProvinceCounty) {
		this.stateProvinceCounty = stateProvinceCounty;
	}

	@Column(name = "country", nullable = false, length = 100)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "other_address_details", nullable = false, length = 100)
	public String getOtherAddressDetails() {
		return this.otherAddressDetails;
	}

	public void setOtherAddressDetails(String otherAddressDetails) {
		this.otherAddressDetails = otherAddressDetails;
	}
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "addresses")
	public Set<Offcers> getOffcerses() {
		return this.offcerses;
	}

	public void setOffcerses(Set<Offcers> offcerses) {
		this.offcerses = offcerses;
	}
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "addresses")
	public Set<Violaters> getViolaterses() {
		return this.violaterses;
	}

	public void setViolaterses(Set<Violaters> violaterses) {
		this.violaterses = violaterses;
	}

}
