package vn.ifisolution.fresher12.entity;
// Generated Sep 27, 2017 3:33:14 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Offcers generated by hbm2java
 */
@Entity
@Table(name = "offcers", catalog = "ThienAn")
public class Offcers implements java.io.Serializable {

	private Integer officerBadgeNumber;
	private Addresses addresses;
	private String gender;
	private String dateOfBirth;
	private String officerFirstName;
	private String officerMiddleName;
	private String officerLastName;		
	private String otherViolaterDetais;
	private Set<Violations> violationses = new HashSet<Violations>(0);

	public Offcers() {
	}

	public Offcers(Addresses addresses, String gender, String dateOfBirth, String officerFirstName,
			String officerMiddleName, String officerLastName, String otherViolaterDetais) {
		this.addresses = addresses;
		this.gender = gender;
		this.dateOfBirth = dateOfBirth;
		this.officerFirstName = officerFirstName;
		this.officerMiddleName = officerMiddleName;
		this.officerLastName = officerLastName;
		this.otherViolaterDetais = otherViolaterDetais;
	}

	public Offcers(Addresses addresses, String gender, String dateOfBirth, String officerFirstName,
			String officerMiddleName, String officerLastName, String otherViolaterDetais,
			Set<Violations> violationses) {
		this.addresses = addresses;
		this.gender = gender;
		this.dateOfBirth = dateOfBirth;
		this.officerFirstName = officerFirstName;
		this.officerMiddleName = officerMiddleName;
		this.officerLastName = officerLastName;
		this.otherViolaterDetais = otherViolaterDetais;
		this.violationses = violationses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "officer_badge_number", unique = true, nullable = false)
	public Integer getOfficerBadgeNumber() {
		return this.officerBadgeNumber;
	}

	public void setOfficerBadgeNumber(Integer officerBadgeNumber) {
		this.officerBadgeNumber = officerBadgeNumber;
	}
	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "officer_address_id", nullable = true)
	public Addresses getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Addresses addresses) {
		this.addresses = addresses;
	}

	@Column(name = "gender", nullable = false, length = 20)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "date_of_birth", nullable = false, length = 20)
	public String getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(String dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	@Column(name = "officer_first_name", nullable = false, length = 50)
	public String getOfficerFirstName() {
		return this.officerFirstName;
	}

	public void setOfficerFirstName(String officerFirstName) {
		this.officerFirstName = officerFirstName;
	}

	@Column(name = "officer_middle_name", nullable = false, length = 50)
	public String getOfficerMiddleName() {
		return this.officerMiddleName;
	}

	public void setOfficerMiddleName(String officerMiddleName) {
		this.officerMiddleName = officerMiddleName;
	}

	@Column(name = "officer_last_name", nullable = false, length = 50)
	public String getOfficerLastName() {
		return this.officerLastName;
	}

	public void setOfficerLastName(String officerLastName) {
		this.officerLastName = officerLastName;
	}

	@Column(name = "other_violater_detais", nullable = false, length = 100)
	public String getOtherViolaterDetais() {
		return this.otherViolaterDetais;
	}

	public void setOtherViolaterDetais(String otherViolaterDetais) {
		this.otherViolaterDetais = otherViolaterDetais;
	}
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "offcers")
	public Set<Violations> getViolationses() {
		return this.violationses;
	}

	public void setViolationses(Set<Violations> violationses) {
		this.violationses = violationses;
	}

}
