package vn.ifisolution.fresher12.entity;
// Generated Sep 27, 2017 3:33:14 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefPaymentMethods generated by hbm2java
 */
@Entity
@Table(name = "Ref_Payment_Methods", catalog = "ThienAn")
public class RefPaymentMethods implements java.io.Serializable {

	private Integer paymentMethodCode;
	private String paymentMethodDescription;
	private Set<Violaters> violaterses = new HashSet<Violaters>(0);

	public RefPaymentMethods() {
	}

	public RefPaymentMethods(String paymentMethodDescription) {
		this.paymentMethodDescription = paymentMethodDescription;
	}

	public RefPaymentMethods(String paymentMethodDescription, Set<Violaters> violaterses) {
		this.paymentMethodDescription = paymentMethodDescription;
		this.violaterses = violaterses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "payment_method_code", unique = true, nullable = false)
	public Integer getPaymentMethodCode() {
		return this.paymentMethodCode;
	}

	public void setPaymentMethodCode(Integer paymentMethodCode) {
		this.paymentMethodCode = paymentMethodCode;
	}

	@Column(name = "payment_method_description", nullable = false, length = 50)
	public String getPaymentMethodDescription() {
		return this.paymentMethodDescription;
	}

	public void setPaymentMethodDescription(String paymentMethodDescription) {
		this.paymentMethodDescription = paymentMethodDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refPaymentMethods")
	public Set<Violaters> getViolaterses() {
		return this.violaterses;
	}

	public void setViolaterses(Set<Violaters> violaterses) {
		this.violaterses = violaterses;
	}

}
