package vn.ifisolution.fresher12.entity;
// Generated Sep 27, 2017 3:33:14 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefTicketStatus generated by hbm2java
 */
@Entity
@Table(name = "Ref_Ticket_Status", catalog = "ThienAn")
public class RefTicketStatus implements java.io.Serializable {

	private Integer ticketStatusCode;
	private String ticketStatusDescription;
	private Set<Tickets> ticketses = new HashSet<Tickets>(0);

	public RefTicketStatus() {
	}

	public RefTicketStatus(String ticketStatusDescription) {
		this.ticketStatusDescription = ticketStatusDescription;
	}

	public RefTicketStatus(String ticketStatusDescription, Set<Tickets> ticketses) {
		this.ticketStatusDescription = ticketStatusDescription;
		this.ticketses = ticketses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ticket_status_code", unique = true, nullable = false)
	public Integer getTicketStatusCode() {
		return this.ticketStatusCode;
	}

	public void setTicketStatusCode(Integer ticketStatusCode) {
		this.ticketStatusCode = ticketStatusCode;
	}

	@Column(name = "ticket_status_description", nullable = false, length = 50)
	public String getTicketStatusDescription() {
		return this.ticketStatusDescription;
	}

	public void setTicketStatusDescription(String ticketStatusDescription) {
		this.ticketStatusDescription = ticketStatusDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refTicketStatus")
	public Set<Tickets> getTicketses() {
		return this.ticketses;
	}

	public void setTicketses(Set<Tickets> ticketses) {
		this.ticketses = ticketses;
	}

}
