package vn.ifisolution.fresher12.entity;
// Generated Sep 27, 2017 3:33:14 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefVehicleTypes generated by hbm2java
 */
@Entity
@Table(name = "Ref_Vehicle_Types", catalog = "ThienAn")
public class RefVehicleTypes implements java.io.Serializable {

	private Integer vehicleTypeCode;
	private String vehicleTypeDescription;
	private Set<Vehicles> vehicleses = new HashSet<Vehicles>(0);

	public RefVehicleTypes() {
	}

	public RefVehicleTypes(String vehicleTypeDescription) {
		this.vehicleTypeDescription = vehicleTypeDescription;
	}

	public RefVehicleTypes(String vehicleTypeDescription, Set<Vehicles> vehicleses) {
		this.vehicleTypeDescription = vehicleTypeDescription;
		this.vehicleses = vehicleses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "vehicle_type_code", unique = true, nullable = false)
	public Integer getVehicleTypeCode() {
		return this.vehicleTypeCode;
	}

	public void setVehicleTypeCode(Integer vehicleTypeCode) {
		this.vehicleTypeCode = vehicleTypeCode;
	}

	@Column(name = "vehicle_type_description", nullable = false, length = 50)
	public String getVehicleTypeDescription() {
		return this.vehicleTypeDescription;
	}

	public void setVehicleTypeDescription(String vehicleTypeDescription) {
		this.vehicleTypeDescription = vehicleTypeDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refVehicleTypes")
	public Set<Vehicles> getVehicleses() {
		return this.vehicleses;
	}

	public void setVehicleses(Set<Vehicles> vehicleses) {
		this.vehicleses = vehicleses;
	}

}
