package vn.ifisolution.fresher12.entity;
// Generated Sep 27, 2017 3:33:14 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefVehicleManufacturers generated by hbm2java
 */
@Entity
@Table(name = "Ref_Vehicle_Manufacturers", catalog = "ThienAn")
public class RefVehicleManufacturers implements java.io.Serializable {

	private Integer manufacturerCode;
	private String manufacturerName;
	private Set<Vehicles> vehicleses = new HashSet<Vehicles>(0);

	public RefVehicleManufacturers() {
	}

	public RefVehicleManufacturers(String manufacturerName) {
		this.manufacturerName = manufacturerName;
	}

	public RefVehicleManufacturers(String manufacturerName, Set<Vehicles> vehicleses) {
		this.manufacturerName = manufacturerName;
		this.vehicleses = vehicleses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "manufacturer_code", unique = true, nullable = false)
	public Integer getManufacturerCode() {
		return this.manufacturerCode;
	}

	public void setManufacturerCode(Integer manufacturerCode) {
		this.manufacturerCode = manufacturerCode;
	}

	@Column(name = "manufacturer_name", nullable = false, length = 50)
	public String getManufacturerName() {
		return this.manufacturerName;
	}

	public void setManufacturerName(String manufacturerName) {
		this.manufacturerName = manufacturerName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refVehicleManufacturers")
	public Set<Vehicles> getVehicleses() {
		return this.vehicleses;
	}

	public void setVehicleses(Set<Vehicles> vehicleses) {
		this.vehicleses = vehicleses;
	}

}
