package vn.ifisolution.fresher12.entity;
// Generated Sep 27, 2017 3:33:14 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vehicles generated by hbm2java
 */
@Entity
@Table(name = "Vehicles", catalog = "ThienAn")
public class Vehicles implements java.io.Serializable {

	private Integer vehicleLicenceNumber;
	private RefVehicleManufacturers refVehicleManufacturers;
	private RefVehicleTypes refVehicleTypes;
	private String yearOfManufacture;
	private String vehicleDetails;
	private String model;
	private Set<ViolaterVehicles> violaterVehicleses = new HashSet<ViolaterVehicles>(0);

	public Vehicles() {
	}

	public Vehicles(RefVehicleManufacturers refVehicleManufacturers, RefVehicleTypes refVehicleTypes,
			String yearOfManufacture, String vehicleDetails, String model) {
		this.refVehicleManufacturers = refVehicleManufacturers;
		this.refVehicleTypes = refVehicleTypes;
		this.yearOfManufacture = yearOfManufacture;
		this.vehicleDetails = vehicleDetails;
		this.model = model;
	}

	public Vehicles(RefVehicleManufacturers refVehicleManufacturers, RefVehicleTypes refVehicleTypes,
			String yearOfManufacture, String vehicleDetails, String model, Set<ViolaterVehicles> violaterVehicleses) {
		this.refVehicleManufacturers = refVehicleManufacturers;
		this.refVehicleTypes = refVehicleTypes;
		this.yearOfManufacture = yearOfManufacture;
		this.vehicleDetails = vehicleDetails;
		this.model = model;
		this.violaterVehicleses = violaterVehicleses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "vehicle_licence_number", unique = true, nullable = false)
	public Integer getVehicleLicenceNumber() {
		return this.vehicleLicenceNumber;
	}

	public void setVehicleLicenceNumber(Integer vehicleLicenceNumber) {
		this.vehicleLicenceNumber = vehicleLicenceNumber;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "manufacturer_code", nullable = false)
	public RefVehicleManufacturers getRefVehicleManufacturers() {
		return this.refVehicleManufacturers;
	}

	public void setRefVehicleManufacturers(RefVehicleManufacturers refVehicleManufacturers) {
		this.refVehicleManufacturers = refVehicleManufacturers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vehicle_type_code", nullable = false)
	public RefVehicleTypes getRefVehicleTypes() {
		return this.refVehicleTypes;
	}

	public void setRefVehicleTypes(RefVehicleTypes refVehicleTypes) {
		this.refVehicleTypes = refVehicleTypes;
	}

	@Column(name = "year_of_manufacture", nullable = false, length = 50)
	public String getYearOfManufacture() {
		return this.yearOfManufacture;
	}

	public void setYearOfManufacture(String yearOfManufacture) {
		this.yearOfManufacture = yearOfManufacture;
	}

	@Column(name = "vehicle_details", nullable = false, length = 50)
	public String getVehicleDetails() {
		return this.vehicleDetails;
	}

	public void setVehicleDetails(String vehicleDetails) {
		this.vehicleDetails = vehicleDetails;
	}

	@Column(name = "model", nullable = false, length = 50)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vehicles")
	public Set<ViolaterVehicles> getViolaterVehicleses() {
		return this.violaterVehicleses;
	}

	public void setViolaterVehicleses(Set<ViolaterVehicles> violaterVehicleses) {
		this.violaterVehicleses = violaterVehicleses;
	}

}
