package vn.ifisolution.fresher12.entity;
// Generated Sep 27, 2017 3:33:14 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ViolaterVehicles generated by hbm2java
 */
@Entity
@Table(name = "violater_vehicles", catalog = "ThienAn")
public class ViolaterVehicles implements java.io.Serializable {

	private Integer violaterId;
	private Vehicles vehicles;
	private Violaters violaters;

	public ViolaterVehicles() {
	}

	public ViolaterVehicles(Vehicles vehicles, Violaters violaters) {
		this.vehicles = vehicles;
		this.violaters = violaters;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "violaters"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "violater_id", unique = true, nullable = false)
	public Integer getViolaterId() {
		return this.violaterId;
	}

	public void setViolaterId(Integer violaterId) {
		this.violaterId = violaterId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vehicle_licence_number", nullable = false)
	public Vehicles getVehicles() {
		return this.vehicles;
	}

	public void setVehicles(Vehicles vehicles) {
		this.vehicles = vehicles;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Violaters getViolaters() {
		return this.violaters;
	}

	public void setViolaters(Violaters violaters) {
		this.violaters = violaters;
	}

}
