package vn.ifisolution.fresher12.entity;
// Generated Sep 27, 2017 3:33:14 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Violations generated by hbm2java
 */
@Entity
@Table(name = "Violations", catalog = "ThienAn")
public class Violations implements java.io.Serializable {

	private Integer violationId;
	private Offcers offcers;
	private RefDocumentTypes refDocumentTypes;
	private int violaterId;
	private int vehicleLicenceNumber;
	private String datetimeViolation;
	private String datetuneOrderDelivered;
	private String otherOffenceDetais;
	private Set<Tickets> ticketses = new HashSet<Tickets>(0);

	public Violations() {
	}

	public Violations(Offcers offcers, RefDocumentTypes refDocumentTypes, int violaterId, int vehicleLicenceNumber,
			String datetimeViolation, String datetuneOrderDelivered, String otherOffenceDetais) {
		this.offcers = offcers;
		this.refDocumentTypes = refDocumentTypes;
		this.violaterId = violaterId;
		this.vehicleLicenceNumber = vehicleLicenceNumber;
		this.datetimeViolation = datetimeViolation;
		this.datetuneOrderDelivered = datetuneOrderDelivered;
		this.otherOffenceDetais = otherOffenceDetais;
	}

	public Violations(Offcers offcers, RefDocumentTypes refDocumentTypes, int violaterId, int vehicleLicenceNumber,
			String datetimeViolation, String datetuneOrderDelivered, String otherOffenceDetais,
			Set<Tickets> ticketses) {
		this.offcers = offcers;
		this.refDocumentTypes = refDocumentTypes;
		this.violaterId = violaterId;
		this.vehicleLicenceNumber = vehicleLicenceNumber;
		this.datetimeViolation = datetimeViolation;
		this.datetuneOrderDelivered = datetuneOrderDelivered;
		this.otherOffenceDetais = otherOffenceDetais;
		this.ticketses = ticketses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "violation_id", unique = true, nullable = false)
	public Integer getViolationId() {
		return this.violationId;
	}

	public void setViolationId(Integer violationId) {
		this.violationId = violationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "officer_badge_number", nullable = false)
	public Offcers getOffcers() {
		return this.offcers;
	}

	public void setOffcers(Offcers offcers) {
		this.offcers = offcers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "document_type_code", nullable = false)
	public RefDocumentTypes getRefDocumentTypes() {
		return this.refDocumentTypes;
	}

	public void setRefDocumentTypes(RefDocumentTypes refDocumentTypes) {
		this.refDocumentTypes = refDocumentTypes;
	}

	@Column(name = "violater_id", nullable = false)
	public int getViolaterId() {
		return this.violaterId;
	}

	public void setViolaterId(int violaterId) {
		this.violaterId = violaterId;
	}

	@Column(name = "vehicle_licence_number", nullable = false)
	public int getVehicleLicenceNumber() {
		return this.vehicleLicenceNumber;
	}

	public void setVehicleLicenceNumber(int vehicleLicenceNumber) {
		this.vehicleLicenceNumber = vehicleLicenceNumber;
	}

	@Column(name = "datetime_violation", nullable = false, length = 50)
	public String getDatetimeViolation() {
		return this.datetimeViolation;
	}

	public void setDatetimeViolation(String datetimeViolation) {
		this.datetimeViolation = datetimeViolation;
	}

	@Column(name = "datetune_order_delivered", nullable = false, length = 50)
	public String getDatetuneOrderDelivered() {
		return this.datetuneOrderDelivered;
	}

	public void setDatetuneOrderDelivered(String datetuneOrderDelivered) {
		this.datetuneOrderDelivered = datetuneOrderDelivered;
	}

	@Column(name = "other_offence_detais", nullable = false, length = 50)
	public String getOtherOffenceDetais() {
		return this.otherOffenceDetais;
	}

	public void setOtherOffenceDetais(String otherOffenceDetais) {
		this.otherOffenceDetais = otherOffenceDetais;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "violations")
	public Set<Tickets> getTicketses() {
		return this.ticketses;
	}

	public void setTicketses(Set<Tickets> ticketses) {
		this.ticketses = ticketses;
	}

}
