package vn.ifisolution.fresher12.entity;
// Generated Sep 27, 2017 3:33:14 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Violaters generated by hbm2java
 */
@Entity
@Table(name = "Violaters", catalog = "ThienAn")
public class Violaters implements java.io.Serializable {

	private int violaterId;
	private Addresses addresses;
	private RefPaymentMethods refPaymentMethods;
	private String violaterName;
	private String violaterPhone;
	private String violaterEmail;
	private String dateOfFirstViolation;
	private String otherViolaterDetais;
	private ViolaterVehicles violaterVehicles;

	public Violaters() {
	}

	public Violaters(int violaterId, Addresses addresses, RefPaymentMethods refPaymentMethods, String violaterName,
			String violaterPhone, String violaterEmail, String dateOfFirstViolation, String otherViolaterDetais) {
		this.violaterId = violaterId;
		this.addresses = addresses;
		this.refPaymentMethods = refPaymentMethods;
		this.violaterName = violaterName;
		this.violaterPhone = violaterPhone;
		this.violaterEmail = violaterEmail;
		this.dateOfFirstViolation = dateOfFirstViolation;
		this.otherViolaterDetais = otherViolaterDetais;
	}

	public Violaters(int violaterId, Addresses addresses, RefPaymentMethods refPaymentMethods, String violaterName,
			String violaterPhone, String violaterEmail, String dateOfFirstViolation, String otherViolaterDetais,
			ViolaterVehicles violaterVehicles) {
		this.violaterId = violaterId;
		this.addresses = addresses;
		this.refPaymentMethods = refPaymentMethods;
		this.violaterName = violaterName;
		this.violaterPhone = violaterPhone;
		this.violaterEmail = violaterEmail;
		this.dateOfFirstViolation = dateOfFirstViolation;
		this.otherViolaterDetais = otherViolaterDetais;
		this.violaterVehicles = violaterVehicles;
	}

	@Id

	@Column(name = "violater_id", unique = true, nullable = false)
	public int getViolaterId() {
		return this.violaterId;
	}

	public void setViolaterId(int violaterId) {
		this.violaterId = violaterId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "violater_address_id", nullable = false)
	public Addresses getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Addresses addresses) {
		this.addresses = addresses;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payment_method_code", nullable = false)
	public RefPaymentMethods getRefPaymentMethods() {
		return this.refPaymentMethods;
	}

	public void setRefPaymentMethods(RefPaymentMethods refPaymentMethods) {
		this.refPaymentMethods = refPaymentMethods;
	}

	@Column(name = "violater_name", nullable = false, length = 20)
	public String getViolaterName() {
		return this.violaterName;
	}

	public void setViolaterName(String violaterName) {
		this.violaterName = violaterName;
	}

	@Column(name = "violater_phone", nullable = false, length = 20)
	public String getViolaterPhone() {
		return this.violaterPhone;
	}

	public void setViolaterPhone(String violaterPhone) {
		this.violaterPhone = violaterPhone;
	}

	@Column(name = "violater_email", nullable = false, length = 50)
	public String getViolaterEmail() {
		return this.violaterEmail;
	}

	public void setViolaterEmail(String violaterEmail) {
		this.violaterEmail = violaterEmail;
	}

	@Column(name = "date_of_first_violation", nullable = false, length = 20)
	public String getDateOfFirstViolation() {
		return this.dateOfFirstViolation;
	}

	public void setDateOfFirstViolation(String dateOfFirstViolation) {
		this.dateOfFirstViolation = dateOfFirstViolation;
	}

	@Column(name = "other_violater_detais", nullable = false, length = 50)
	public String getOtherViolaterDetais() {
		return this.otherViolaterDetais;
	}

	public void setOtherViolaterDetais(String otherViolaterDetais) {
		this.otherViolaterDetais = otherViolaterDetais;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "violaters")
	public ViolaterVehicles getViolaterVehicles() {
		return this.violaterVehicles;
	}

	public void setViolaterVehicles(ViolaterVehicles violaterVehicles) {
		this.violaterVehicles = violaterVehicles;
	}

}
