package vn.ifisolution.fresher12.entity;
// Generated Sep 27, 2017 3:33:14 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;

import org.springframework.data.annotation.Id;
import org.springframework.data.cassandra.mapping.Column;
import org.springframework.data.cassandra.mapping.PrimaryKey;
import org.springframework.data.cassandra.mapping.Table;

/**
 * Addresses generated by hbm2java
 */

@Table("addresses")
public class Addresses implements java.io.Serializable {
	@PrimaryKey 
	private Integer address_id;
	private String line_1_number_building;
	private String line_2_number_street;
	private String line_3_area_localyti_suburb;
	private String line_4_other;
	private String town_city;
	private String zip_postcode;
	private String state_province_county;
	private String country;
	private String other_address_details;
	private Set<Offcers> offcerses = new HashSet<Offcers>(0);
	private Set<Violaters> violaterses = new HashSet<Violaters>(0);
	public Integer getAddress_id() {
		return address_id;
	}
	public void setAddress_id(Integer address_id) {
		this.address_id = address_id;
	}
	public String getLine_1_number_building() {
		return line_1_number_building;
	}
	public void setLine_1_number_building(String line_1_number_building) {
		this.line_1_number_building = line_1_number_building;
	}
	public String getLine_2_number_street() {
		return line_2_number_street;
	}
	public void setLine_2_number_street(String line_2_number_street) {
		this.line_2_number_street = line_2_number_street;
	}
	public String getLine_3_area_localyti_suburb() {
		return line_3_area_localyti_suburb;
	}
	public void setLine_3_area_localyti_suburb(String line_3_area_localyti_suburb) {
		this.line_3_area_localyti_suburb = line_3_area_localyti_suburb;
	}
	public String getLine_4_other() {
		return line_4_other;
	}
	public void setLine_4_other(String line_4_other) {
		this.line_4_other = line_4_other;
	}
	public String getTown_city() {
		return town_city;
	}
	public void setTown_city(String town_city) {
		this.town_city = town_city;
	}
	public String getZip_postcode() {
		return zip_postcode;
	}
	public void setZip_postcode(String zip_postcode) {
		this.zip_postcode = zip_postcode;
	}
	public String getState_province_county() {
		return state_province_county;
	}
	public void setState_province_county(String state_province_county) {
		this.state_province_county = state_province_county;
	}
	public String getCountry() {
		return country;
	}
	public void setCountry(String country) {
		this.country = country;
	}
	public String getOther_address_details() {
		return other_address_details;
	}
	public void setOther_address_details(String other_address_details) {
		this.other_address_details = other_address_details;
	}
	public Set<Offcers> getOffcerses() {
		return offcerses;
	}
	public void setOffcerses(Set<Offcers> offcerses) {
		this.offcerses = offcerses;
	}
	public Set<Violaters> getViolaterses() {
		return violaterses;
	}
	public void setViolaterses(Set<Violaters> violaterses) {
		this.violaterses = violaterses;
	}
	@Override
	public String toString() {
		return "Addresses [address_id=" + address_id
				+ ", line_1_number_building=" + line_1_number_building
				+ ", line_2_number_street=" + line_2_number_street
				+ ", line_3_area_localyti_suburb="
				+ line_3_area_localyti_suburb + ", line_4_other="
				+ line_4_other + ", town_city=" + town_city + ", zip_postcode="
				+ zip_postcode + ", state_province_county="
				+ state_province_county + ", country=" + country
				+ ", other_address_details=" + other_address_details
				+ ", offcerses=" + offcerses + ", violaterses=" + violaterses
				+ "]";
	}
	public Addresses(Integer address_id, String line_1_number_building,
			String line_2_number_street, String line_3_area_localyti_suburb,
			String line_4_other, String town_city, String zip_postcode,
			String state_province_county, String country,
			String other_address_details, Set<Offcers> offcerses,
			Set<Violaters> violaterses) {
		super();
		this.address_id = address_id;
		this.line_1_number_building = line_1_number_building;
		this.line_2_number_street = line_2_number_street;
		this.line_3_area_localyti_suburb = line_3_area_localyti_suburb;
		this.line_4_other = line_4_other;
		this.town_city = town_city;
		this.zip_postcode = zip_postcode;
		this.state_province_county = state_province_county;
		this.country = country;
		this.other_address_details = other_address_details;
		this.offcerses = offcerses;
		this.violaterses = violaterses;
	}
	public Addresses() {
		super();
		// TODO Auto-generated constructor stub
	}

	
}
