package vn.ifisolution.fresher12.entity;

// Generated Sep 27, 2017 3:33:14 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;

import org.springframework.data.annotation.Id;
import org.springframework.data.cassandra.mapping.Column;
import org.springframework.data.cassandra.mapping.PrimaryKey;
import org.springframework.data.cassandra.mapping.Table;

/**
 * Offcers generated by hbm2java
 */

@Table("offcers")
public class Offcers implements java.io.Serializable {
	@PrimaryKey
	private Integer officer_badge_number;
	private Integer officer_address_id;
	private String gender;
	private String date_of_birth;
	private String officer_first_name;
	private String officer_middle_name;
	private String officer_last_name;
	private String other_violater_detais;
	
	public Integer getOfficer_badge_number() {
		return officer_badge_number;
	}

	public void setOfficer_badge_number(Integer officer_badge_number) {
		this.officer_badge_number = officer_badge_number;
	}

	public Integer getOfficer_address_id() {
		return officer_address_id;
	}

	public void setOfficer_address_id(Integer officer_address_id) {
		this.officer_address_id = officer_address_id;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getDate_of_birth() {
		return date_of_birth;
	}

	public void setDate_of_birth(String date_of_birth) {
		this.date_of_birth = date_of_birth;
	}

	public String getOfficer_first_name() {
		return officer_first_name;
	}

	public void setOfficer_first_name(String officer_first_name) {
		this.officer_first_name = officer_first_name;
	}

	public String getOfficer_middle_name() {
		return officer_middle_name;
	}

	public void setOfficer_middle_name(String officer_middle_name) {
		this.officer_middle_name = officer_middle_name;
	}

	public String getOfficer_last_name() {
		return officer_last_name;
	}

	public void setOfficer_last_name(String officer_last_name) {
		this.officer_last_name = officer_last_name;
	}

	public String getOther_violater_detais() {
		return other_violater_detais;
	}

	public void setOther_violater_detais(String other_violater_detais) {
		this.other_violater_detais = other_violater_detais;
	}

	@Override
	public String toString() {
		return "Offcers [officer_badge_number=" + officer_badge_number
				+ ", officer_address_id=" + officer_address_id + ", gender="
				+ gender + ", date_of_birth=" + date_of_birth
				+ ", officer_first_name=" + officer_first_name
				+ ", officer_middle_name=" + officer_middle_name
				+ ", officer_last_name=" + officer_last_name
				+ ", other_violater_detais=" + other_violater_detais + "]";
	}

	public Offcers(Integer officer_badge_number, Integer officer_address_id,
			String gender, String date_of_birth, String officer_first_name,
			String officer_middle_name, String officer_last_name,
			String other_violater_detais) {
		super();
		this.officer_badge_number = officer_badge_number;
		this.officer_address_id = officer_address_id;
		this.gender = gender;
		this.date_of_birth = date_of_birth;
		this.officer_first_name = officer_first_name;
		this.officer_middle_name = officer_middle_name;
		this.officer_last_name = officer_last_name;
		this.other_violater_detais = other_violater_detais;
	}

	public Offcers() {
		super();
		// TODO Auto-generated constructor stub
	}

}
