package vn.ifisolution.fresher12.entity;
// Generated Sep 27, 2017 3:33:14 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;

import org.springframework.data.annotation.Id;
import org.springframework.data.cassandra.mapping.Column;
import org.springframework.data.cassandra.mapping.PrimaryKey;
import org.springframework.data.cassandra.mapping.Table;

/**
 * RefPaymentMethods generated by hbm2java
 */

@Table("ref_payment_methods")
public class RefPaymentMethods implements java.io.Serializable {
   @PrimaryKey
	private Integer payment_method_code;
	private String payment_method_description;
	public Integer getPayment_method_code() {
		return payment_method_code;
	}
	public void setPayment_method_code(Integer payment_method_code) {
		this.payment_method_code = payment_method_code;
	}
	public String getPayment_method_description() {
		return payment_method_description;
	}
	public void setPayment_method_description(String payment_method_description) {
		this.payment_method_description = payment_method_description;
	}
	public Set<Violaters> getViolaterses() {
		return violaterses;
	}
	public void setViolaterses(Set<Violaters> violaterses) {
		this.violaterses = violaterses;
	}
	public RefPaymentMethods(Integer payment_method_code,
			String payment_method_description, Set<Violaters> violaterses) {
		super();
		this.payment_method_code = payment_method_code;
		this.payment_method_description = payment_method_description;
		this.violaterses = violaterses;
	}
	public RefPaymentMethods() {
		super();
		// TODO Auto-generated constructor stub
	}
	private Set<Violaters> violaterses = new HashSet<Violaters>(0);

	

}
