package vn.ifisolution.fresher12.entity;
// Generated Sep 27, 2017 3:33:14 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;

import org.springframework.data.annotation.Id;
import org.springframework.data.cassandra.mapping.Column;
import org.springframework.data.cassandra.mapping.PrimaryKey;
import org.springframework.data.cassandra.mapping.Table;

/**
 * RefTicketStatus generated by hbm2java
 */
@Table("ref_Ticket_Status")
public class RefTicketStatus implements java.io.Serializable {
   @PrimaryKey
	private Integer ticket_status_code;
	private String ticket_status_description;
	public RefTicketStatus(Integer ticket_status_code,
			String ticket_status_description, Set<Tickets> ticketses) {
		super();
		this.ticket_status_code = ticket_status_code;
		this.ticket_status_description = ticket_status_description;
		this.ticketses = ticketses;
	}
	public RefTicketStatus() {
		super();
		// TODO Auto-generated constructor stub
	}
	private Set<Tickets> ticketses = new HashSet<Tickets>(0);
	public Integer getTicket_status_code() {
		return ticket_status_code;
	}
	public void setTicket_status_code(Integer ticket_status_code) {
		this.ticket_status_code = ticket_status_code;
	}
	public String getTicket_status_description() {
		return ticket_status_description;
	}
	public void setTicket_status_description(String ticket_status_description) {
		this.ticket_status_description = ticket_status_description;
	}
	public Set<Tickets> getTicketses() {
		return ticketses;
	}
	public void setTicketses(Set<Tickets> ticketses) {
		this.ticketses = ticketses;
	}

	

}
