package vn.ifisolution.fresher12.entity;
// Generated Sep 27, 2017 3:33:14 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;

import org.springframework.data.annotation.Id;
import org.springframework.data.cassandra.mapping.Column;
import org.springframework.data.cassandra.mapping.PrimaryKey;
import org.springframework.data.cassandra.mapping.Table;

/**
 * RefVehicleManufacturers generated by hbm2java
 */

@Table("ref_Vehicle_Manufacturers")
public class RefVehicleManufacturers implements java.io.Serializable {
	 @PrimaryKey
	private Integer manufacturer_code;
	private String manufacturer_name;
	public Integer getManufacturer_code() {
		return manufacturer_code;
	}
	public void setManufacturer_code(Integer manufacturer_code) {
		this.manufacturer_code = manufacturer_code;
	}
	public String getManufacturer_name() {
		return manufacturer_name;
	}
	public void setManufacturer_name(String manufacturer_name) {
		this.manufacturer_name = manufacturer_name;
	}
	public Set<Vehicles> getVehicleses() {
		return vehicleses;
	}
	public void setVehicleses(Set<Vehicles> vehicleses) {
		this.vehicleses = vehicleses;
	}
	public RefVehicleManufacturers() {
		super();
		// TODO Auto-generated constructor stub
	}
	public RefVehicleManufacturers(Integer manufacturer_code,
			String manufacturer_name, Set<Vehicles> vehicleses) {
		super();
		this.manufacturer_code = manufacturer_code;
		this.manufacturer_name = manufacturer_name;
		this.vehicleses = vehicleses;
	}
	private Set<Vehicles> vehicleses = new HashSet<Vehicles>(0);

	

}
