package vn.ifisolution.fresher12.entity;
// Generated Sep 27, 2017 3:33:14 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;

import org.springframework.data.annotation.Id;
import org.springframework.data.cassandra.mapping.Column;
import org.springframework.data.cassandra.mapping.PrimaryKey;
import org.springframework.data.cassandra.mapping.Table;

/**
 * RefVehicleTypes generated by hbm2java
 */
@Table("ref_Vehicle_Types")
public class RefVehicleTypes implements java.io.Serializable {
	 @PrimaryKey
	private Integer vehicle_type_code;
	private String vehicle_type_description;
	public Integer getVehicle_type_code() {
		return vehicle_type_code;
	}
	public void setVehicle_type_code(Integer vehicle_type_code) {
		this.vehicle_type_code = vehicle_type_code;
	}
	public String getVehicle_type_description() {
		return vehicle_type_description;
	}
	public void setVehicle_type_description(String vehicle_type_description) {
		this.vehicle_type_description = vehicle_type_description;
	}
	public Set<Vehicles> getVehicleses() {
		return vehicleses;
	}
	public void setVehicleses(Set<Vehicles> vehicleses) {
		this.vehicleses = vehicleses;
	}
	public RefVehicleTypes(Integer vehicle_type_code,
			String vehicle_type_description, Set<Vehicles> vehicleses) {
		super();
		this.vehicle_type_code = vehicle_type_code;
		this.vehicle_type_description = vehicle_type_description;
		this.vehicleses = vehicleses;
	}
	public RefVehicleTypes() {
		super();
		// TODO Auto-generated constructor stub
	}
	private Set<Vehicles> vehicleses = new HashSet<Vehicles>(0);

	
}
