package vn.ifisolution.fresher12.entity;

// Generated Sep 27, 2017 3:33:14 PM by Hibernate Tools 5.2.5.Final

import org.springframework.data.annotation.Id;
import org.springframework.data.cassandra.mapping.Column;
import org.springframework.data.cassandra.mapping.PrimaryKey;
import org.springframework.data.cassandra.mapping.Table;

/**
 * Tickets generated by hbm2java
 */

@Table("tickets")
public class Tickets implements java.io.Serializable {
	@PrimaryKey
	private Integer ticket_number;
	private RefTicketStatus ref_ticket_status;
	private Violations violations;
	private String date_ticket_cabcelled;
	private String date_ticket_paid;
	private String other_ticket_detais;
	public Integer getTicket_number() {
		return ticket_number;
	}
	public void setTicket_number(Integer ticket_number) {
		this.ticket_number = ticket_number;
	}
	public RefTicketStatus getRef_ticket_status() {
		return ref_ticket_status;
	}
	public void setRef_ticket_status(RefTicketStatus ref_ticket_status) {
		this.ref_ticket_status = ref_ticket_status;
	}
	public Violations getViolations() {
		return violations;
	}
	public void setViolations(Violations violations) {
		this.violations = violations;
	}
	public String getDate_ticket_cabcelled() {
		return date_ticket_cabcelled;
	}
	public void setDate_ticket_cabcelled(String date_ticket_cabcelled) {
		this.date_ticket_cabcelled = date_ticket_cabcelled;
	}
	public String getDate_ticket_paid() {
		return date_ticket_paid;
	}
	public void setDate_ticket_paid(String date_ticket_paid) {
		this.date_ticket_paid = date_ticket_paid;
	}
	public String getOther_ticket_detais() {
		return other_ticket_detais;
	}
	public void setOther_ticket_detais(String other_ticket_detais) {
		this.other_ticket_detais = other_ticket_detais;
	}
	public Tickets(Integer ticket_number, RefTicketStatus ref_ticket_status,
			Violations violations, String date_ticket_cabcelled,
			String date_ticket_paid, String other_ticket_detais) {
		super();
		this.ticket_number = ticket_number;
		this.ref_ticket_status = ref_ticket_status;
		this.violations = violations;
		this.date_ticket_cabcelled = date_ticket_cabcelled;
		this.date_ticket_paid = date_ticket_paid;
		this.other_ticket_detais = other_ticket_detais;
	}
	public Tickets() {
		super();
		// TODO Auto-generated constructor stub
	}

	

}
