package vn.ifisolution.fresher12.entity;
// Generated Sep 27, 2017 3:33:14 PM by Hibernate Tools 5.2.5.Final

import org.springframework.data.annotation.Id;
import org.springframework.data.cassandra.mapping.Column;
import org.springframework.data.cassandra.mapping.PrimaryKey;
import org.springframework.data.cassandra.mapping.Table;

/**
 * ViolaterVehicles generated by hbm2java
 */

@Table("violater_vehicles")
public class ViolaterVehicles implements java.io.Serializable {
    @PrimaryKey
	private Integer violater_dd;
	private Vehicles vehicles;
	private Violaters violaters;
	public Integer getViolater_dd() {
		return violater_dd;
	}
	public void setViolater_dd(Integer violater_dd) {
		this.violater_dd = violater_dd;
	}
	public Vehicles getVehicles() {
		return vehicles;
	}
	public void setVehicles(Vehicles vehicles) {
		this.vehicles = vehicles;
	}
	public Violaters getViolaters() {
		return violaters;
	}
	public void setViolaters(Violaters violaters) {
		this.violaters = violaters;
	}
	public ViolaterVehicles(Integer violater_dd, Vehicles vehicles,
			Violaters violaters) {
		super();
		this.violater_dd = violater_dd;
		this.vehicles = vehicles;
		this.violaters = violaters;
	}
	public ViolaterVehicles() {
		super();
		// TODO Auto-generated constructor stub
	}

	
}
