package vn.ifisolution.fresher12.entity;

// Generated Sep 27, 2017 3:33:14 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;

import org.springframework.data.annotation.Id;
import org.springframework.data.cassandra.mapping.Column;
import org.springframework.data.cassandra.mapping.PrimaryKey;
import org.springframework.data.cassandra.mapping.Table;

/**
 * Violations generated by hbm2java
 */

@Table("violations")
public class Violations implements java.io.Serializable {
	@PrimaryKey
	private Integer violation_id;
	private Offcers offcers;
	private RefDocumentTypes ref_document_types;
	private int violater_id;
	private int vehicle_licence_number;
	private String datetime_violation;
	private String datetune_order_delivered;
	private String other_offence_detais;
	public Violations(Integer violation_id, Offcers offcers,
			RefDocumentTypes ref_document_types, int violater_id,
			int vehicle_licence_number, String datetime_violation,
			String datetune_order_delivered, String other_offence_detais,
			Set<Tickets> ticketses) {
		super();
		this.violation_id = violation_id;
		this.offcers = offcers;
		this.ref_document_types = ref_document_types;
		this.violater_id = violater_id;
		this.vehicle_licence_number = vehicle_licence_number;
		this.datetime_violation = datetime_violation;
		this.datetune_order_delivered = datetune_order_delivered;
		this.other_offence_detais = other_offence_detais;
		this.ticketses = ticketses;
	}
	public Integer getViolation_id() {
		return violation_id;
	}
	public void setViolation_id(Integer violation_id) {
		this.violation_id = violation_id;
	}
	public Offcers getOffcers() {
		return offcers;
	}
	public void setOffcers(Offcers offcers) {
		this.offcers = offcers;
	}
	public RefDocumentTypes getRef_document_types() {
		return ref_document_types;
	}
	public void setRef_document_types(RefDocumentTypes ref_document_types) {
		this.ref_document_types = ref_document_types;
	}
	public int getViolater_id() {
		return violater_id;
	}
	public void setViolater_id(int violater_id) {
		this.violater_id = violater_id;
	}
	public int getVehicle_licence_number() {
		return vehicle_licence_number;
	}
	public void setVehicle_licence_number(int vehicle_licence_number) {
		this.vehicle_licence_number = vehicle_licence_number;
	}
	public String getDatetime_violation() {
		return datetime_violation;
	}
	public void setDatetime_violation(String datetime_violation) {
		this.datetime_violation = datetime_violation;
	}
	public String getDatetune_order_delivered() {
		return datetune_order_delivered;
	}
	public void setDatetune_order_delivered(String datetune_order_delivered) {
		this.datetune_order_delivered = datetune_order_delivered;
	}
	public String getOther_offence_detais() {
		return other_offence_detais;
	}
	public void setOther_offence_detais(String other_offence_detais) {
		this.other_offence_detais = other_offence_detais;
	}
	public Set<Tickets> getTicketses() {
		return ticketses;
	}
	public void setTicketses(Set<Tickets> ticketses) {
		this.ticketses = ticketses;
	}
	public Violations() {
		super();
		// TODO Auto-generated constructor stub
	}
	private Set<Tickets> ticketses = new HashSet<Tickets>(0);


}
